### ISSUE TITLE
Shame you got banned.

### ISSUE THREAD

**Issue by SuperKael** [BepInEx/BepInEx.uMod.Loader#1]
Unfortunately, the UMF developer has a rather unpleasant personality, so it’s no surprise you got banned from his Discord. Are there any other places where you’ve shared this? It would be nice to see if and how this is being used, and it would be a shame for your efforts to go to waste. I previously used UMF in my own modding efforts, but ended up moving away from it mostly because of its developer.

**Comment by bbepis** [comment]
I've uploaded a functional instance of this to https://www.nexusmods.com/slimerancher/mods/176 with an SRML emulator as well.

However DracoClaw is trying to get people to spam report it to try and get it taken down (even though I've fully adhered to SRML's GPL v3.0 license) simply because I forked it *without asking for permission*. Which is very strange considering that Draco isn't even a developer for it; veesus is the actual developer and has been completely non-vocal about it even when I asked.

![image](https://user-images.githubusercontent.com/36346617/127523394-94a71ef4-d923-4a6a-a773-5237e860af95.png)

From what I've heard Draco is threatening veesus into compliance for some reason, but I'm not sure if it's true.

Frankly I wouldn't have published this to Nexus if he didn't overreact like this. I don't really have any desire to remain within the SR community if it's this toxic.

As for this project, I made it because I saw it as a challenge and had fun doing it. I don't really plan on updating this any more. Not that it matters though, as the next version of UML is probably never going to release. I do agree that the developer for UML is a weird unit; they have a giant anti-opensource manifesto in their discord and loves to call end users stupid.

If you really are interested in content like this, I'd probably suggest taking a look at [my own Unity modloader](https://github.com/BepInEx/BepInEx) as it's the only similar kind of project I more-or-less maintain. (Not to mention that it's much more popular than UML anyway)

**Comment by SuperKael** [comment]
Well that's a shame - clearly this Draco character doesn't understand the point of open source licensing. If you're afraid of people forking your project, then you shouldn't use an open source license. Anyways, thanks for the links, this is very neat!
